name: Staging - Build PR
'on':
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}
  cancel-in-progress: true
jobs:
  build-pr:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: PR Staging @ ${{ github.event.pull_request.head.label }}
      cancel-in-progress: true
    steps:
    - name: Check out repo
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Check changed files
      if: ${{ github.event.pull_request.user.login != 'Octomerger' }}
      uses: dorny/paths-filter@eb75a1edc117d3756a18ef89958ee59f9500ba58
      id: filter
      with:
        base: main
        list-files: json
        filters: "notAllowed:\n  - '*.js'\n  - '*.mjs'\n  - '*.cjs'\n  - '*.ts'\n\
          \  - '*.tsx'\n  - '*.json'\n  - '.npmrc'\n  - '.babelrc*'\n  - '.env*'\n\
          \  - 'script/**'\n  - 'Procfile'\n"
    - name: Fail when disallowed files are changed
      if: ${{ steps.filter.outputs.notAllowed == 'true' }}
      run: exit 1
    - name: Setup node
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
      with:
        node-version: 16.13.x
        cache: npm
    - name: Update to npm@^7.20.0
      run: npm install --global npm@^7.20.0
    - name: Install dependencies
      run: npm ci
    - name: Cache nextjs build
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}
    - name: Build
      run: npm run build
    - name: Remove development-only dependencies
      run: npm prune --production
    - name: Remove all npm scripts
      run: npm pkg delete scripts
    - name: Set npm script for Heroku build to noop
      run: npm set-script heroku-postbuild "echo 'Application was pre-built!'"
    - name: Create an archive
      run: "tar -c --file=app.tar \\\n  node_modules/ \\\n  .next/ \\\n  assets/ \\\
        \n  content/ \\\n  data/ \\\n  includes/ \\\n  lib/ \\\n  middleware/ \\\n\
        \  translations/ \\\n  server.mjs \\\n  package*.json \\\n  .npmrc \\\n  feature-flags.json\
        \ \\\n  next.config.js \\\n  app.json \\\n  Procfile\n\n# We can't delete\
        \ the .next/cache directory from the workflow\n# because it's needed for caching,\
        \ but we can at least delete it\n# from within the tarball. Then it can be\
        \ cached but not\n# weigh down the tarball we intend to deploy.\ntar --delete\
        \ --file=app.tar .next/cache\n"
    - name: Upload build artifact
      uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: pr_build
        path: app.tar
