name: Node.js Tests
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
  pull_request: null
permissions:
  contents: read
  pull-requests: read
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test-group:
        - content
        - graphql
        - meta
        - rendering
        - routing
        - unit
        - linting
        - translations
    steps:
    - name: Check out repo
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        persist-credentials: 'false'
    - name: Gather files changed
      uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
      id: get_diff_files
      with:
        output: ' '
    - name: Insight into changed files
      run: '

        # Must to do this because the list of files can be HUGE. Especially

        # in a repo-sync when there are lots of translation files involved.

        echo "${{ steps.get_diff_files.outputs.files }}" > get_diff_files.txt

        '
    - name: Setup node
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
      with:
        node-version: 16.13.x
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Clone early access
      if: ${{ github.repository == 'github/docs-internal' }}
      run: script/early-access/clone-for-build.js
      env:
        DOCUBOT_REPO_PAT: ${{ secrets.DOCUBOT_REPO_PAT }}
        GIT_BRANCH: ${{ github.head_ref || github.ref }}
    - name: Cache nextjs build
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}
    - name: Run build script
      run: npm run build
    - name: Run tests
      env:
        DIFF_FILE: get_diff_files.txt
      run: npm run test tests/${{ matrix.test-group }}/
